<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobPostingsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('job_postings')->insert([
            [
                'id'              => 1,
                'hr_user_id'      => 1,
                'category_id'     => 1,
                'title'           => 'Backend Developer Laravel',
                'slug'            => 'backend-developer-laravel',
                'description'     => 'Kami mencari Backend Developer yang berpengalaman dalam membangun sistem API menggunakan Laravel. Kandidat akan bertanggung jawab dalam pengembangan dan pemeliharaan sistem rekrutmen digital perusahaan.',
                'requirements'    => 'Minimal S1 Teknik Informatika atau bidang terkait. Pengalaman minimal 1 tahun dengan Laravel. Memahami konsep REST API, MySQL, dan Git.',
                'benefits'        => 'Gaji kompetitif, BPJS Kesehatan & Ketenagakerjaan, bonus kinerja tahunan, lingkungan kerja kondusif.',
                'employment_type' => 'full-time',
                'location_type'   => 'onsite',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 6000000.00,
                'salary_max'      => 10000000.00,
                'show_salary'     => 1,
                'quota'           => 2,
                'applicant_count' => 2,
                'status'          => 'open',
                'deadline'        => '2026-05-26',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
            [
                'id'              => 2,
                'hr_user_id'      => 1,
                'category_id'     => 1,
                'title'           => 'Frontend Developer',
                'slug'            => 'frontend-developer',
                'description'     => 'Dibutuhkan Frontend Developer yang mampu membangun tampilan web yang responsif dan modern menggunakan HTML, CSS, dan JavaScript murni.',
                'requirements'    => 'Minimal D3/S1 jurusan IT. Menguasai HTML5, CSS3, JavaScript. Memahami konsep AJAX dan REST API.',
                'benefits'        => 'Gaji kompetitif, asuransi kesehatan, peluang pengembangan karir.',
                'employment_type' => 'full-time',
                'location_type'   => 'hybrid',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 5000000.00,
                'salary_max'      => 8000000.00,
                'show_salary'     => 1,
                'quota'           => 1,
                'applicant_count' => 1,
                'status'          => 'open',
                'deadline'        => '2026-04-26',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
            [
                'id'              => 3,
                'hr_user_id'      => 2,
                'category_id'     => 2,
                'title'           => 'Staff Keuangan & Akuntansi',
                'slug'            => 'staff-keuangan-akuntansi',
                'description'     => 'Mencari Staff Keuangan yang teliti dan berpengalaman dalam pengelolaan laporan keuangan perusahaan manufaktur.',
                'requirements'    => 'S1 Akuntansi atau Keuangan. Pengalaman minimal 2 tahun. Menguasai software akuntansi dan Microsoft Excel.',
                'benefits'        => 'Gaji sesuai pengalaman, BPJS, tunjangan makan dan transport.',
                'employment_type' => 'full-time',
                'location_type'   => 'onsite',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 5000000.00,
                'salary_max'      => 7000000.00,
                'show_salary'     => 0,
                'quota'           => 1,
                'applicant_count' => 1,
                'status'          => 'open',
                'deadline'        => '2026-05-26',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
            [
                'id'              => 4,
                'hr_user_id'      => 2,
                'category_id'     => 3,
                'title'           => 'HR Recruitment Specialist',
                'slug'            => 'hr-recruitment-specialist',
                'description'     => 'Posisi HR Recruitment untuk mendukung proses rekrutmen internal PT Eco Green Oleochemicals yang terus berkembang.',
                'requirements'    => 'S1 Psikologi atau Manajemen SDM. Pengalaman di bidang rekrutmen minimal 1 tahun. Mampu mengoperasikan sistem HRIS.',
                'benefits'        => 'Gaji kompetitif, pelatihan dan pengembangan karir, lingkungan kerja profesional.',
                'employment_type' => 'full-time',
                'location_type'   => 'onsite',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 5000000.00,
                'salary_max'      => 8000000.00,
                'show_salary'     => 1,
                'quota'           => 1,
                'applicant_count' => 0,
                'status'          => 'open',
                'deadline'        => '2026-06-26',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
            [
                'id'              => 5,
                'hr_user_id'      => 1,
                'category_id'     => 4,
                'title'           => 'Operator Produksi',
                'slug'            => 'operator-produksi',
                'description'     => 'Dibutuhkan Operator Produksi untuk lini produksi oleokimia. Kandidat akan bekerja dalam shift dan bertanggung jawab atas kelancaran proses produksi.',
                'requirements'    => 'Minimal SMA/SMK sederajat. Bersedia bekerja shift. Memiliki pengalaman di industri manufaktur lebih diutamakan.',
                'benefits'        => 'Gaji pokok + tunjangan shift, BPJS, makan siang gratis.',
                'employment_type' => 'full-time',
                'location_type'   => 'onsite',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 3500000.00,
                'salary_max'      => 5000000.00,
                'show_salary'     => 1,
                'quota'           => 5,
                'applicant_count' => 1,
                'status'          => 'open',
                'deadline'        => '2026-04-16',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
            [
                'id'              => 6,
                'hr_user_id'      => 1,
                'category_id'     => 1,
                'title'           => 'IT Support Intern',
                'slug'            => 'it-support-intern',
                'description'     => 'Program magang IT Support untuk mahasiswa aktif semester 5 ke atas. Akan mendapatkan pengalaman nyata dalam pengelolaan infrastruktur IT perusahaan.',
                'requirements'    => 'Mahasiswa aktif D3/S1 jurusan IT. Memahami dasar jaringan komputer. Komunikatif dan cepat belajar.',
                'benefits'        => 'Uang saku harian, sertifikat magang, peluang direkrut sebagai karyawan tetap.',
                'employment_type' => 'internship',
                'location_type'   => 'onsite',
                'location'        => 'Batam, Kepulauan Riau',
                'salary_min'      => 1500000.00,
                'salary_max'      => 2500000.00,
                'show_salary'     => 1,
                'quota'           => 3,
                'applicant_count' => 0,
                'status'          => 'open',
                'deadline'        => '2026-04-26',
                'created_at'      => '2026-03-25 18:18:14',
                'updated_at'      => '2026-03-25 18:18:14',
                'closed_at'       => null,
            ],
        ]);
    }
}
