<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data pengguna awal: 3 HR dan 14 pelamar (termasuk contoh data dummy).
     * Password semua user sudah di-hash dengan bcrypt.
     * HR Login  : hr@ecogreen.com / password: password
     * HR Master : ecorgeen@gmail.com / password: 12345678
     * Applicant  : nouzenshin@gmail.com / password: 12345678
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id'                => 1,
                'name'              => 'Admin HR Eco Green',
                'email'             => 'hr@ecogreen.com',
                'password_hash'     => '$2y$12$DGSQvGS.utxL7ps37yDqyOR7r2LQvBwK0Wj4OEfFqDWJYUcnUJIkG',
                'role'              => 'hr',
                'phone'             => '081234567890',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:07',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:07',
                'updated_at'        => '2026-03-25 18:18:07',
            ],
            [
                'id'                => 2,
                'name'              => 'Siti Rahayu HR',
                'email'             => 'siti.hr@ecogreen.com',
                'password_hash'     => '$2y$12$ulGvi2ZJyb4mXMGGMhK5jeu9xyCQBaf8QsNXMLE6TRZKJJz2PcYhO',
                'role'              => 'hr',
                'phone'             => '081234567891',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:08',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:08',
                'updated_at'        => '2026-03-25 18:18:08',
            ],
            [
                'id'                => 3,
                'name'              => 'Budi Santoso',
                'email'             => 'budi@gmail.com',
                'password_hash'     => '$2y$12$6ANtCZjdrDB6k0i.sFNpG.pWkZln3k5BCDnCAIVWmKtzW8p4O2X/O',
                'role'              => 'applicant',
                'phone'             => '082345678901',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:08',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:08',
                'updated_at'        => '2026-03-25 18:18:08',
            ],
            [
                'id'                => 4,
                'name'              => 'Sari Dewi',
                'email'             => 'sari@gmail.com',
                'password_hash'     => '$2y$12$rs8/lZlKdTumH1mMOQWXUeta8UIBP2nSmbdztMrHXpMOgGceE2V3u',
                'role'              => 'applicant',
                'phone'             => '083456789012',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:08',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:08',
                'updated_at'        => '2026-03-25 18:18:08',
            ],
            [
                'id'                => 5,
                'name'              => 'Ahmad Rizki',
                'email'             => 'rizki@gmail.com',
                'password_hash'     => '$2y$12$20SWmhZERslSjI0A2wqQeuVjBjNXaPgBAypz.LJWIpow6vtosOwju',
                'role'              => 'applicant',
                'phone'             => '084567890123',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:09',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:09',
                'updated_at'        => '2026-03-25 18:18:09',
            ],
            [
                'id'                => 6,
                'name'              => 'Mr. Frankie Schmidt DDS',
                'email'             => 'beer.moses@example.com',
                'password_hash'     => '$2y$12$KCyDRX6NrkMRLmClEZvviuII4e2bYjhBERSQMOj9OPYSDTMbepz9y',
                'role'              => 'applicant',
                'phone'             => '086418562669',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:10',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 7,
                'name'              => 'Milton Howe III',
                'email'             => 'nstehr@example.net',
                'password_hash'     => '$2y$12$H2wqpEmFwxkhC9PPfRxnrunGy.XaPsf1diBd.TTMFJxvBhxaH8q8O',
                'role'              => 'applicant',
                'phone'             => '087714302536',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:10',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 8,
                'name'              => 'Hattie Gerlach DDS',
                'email'             => 'gparisian@example.org',
                'password_hash'     => '$2y$12$l8iqiJDH3hWa3S/DYLUck.IZeiuWlxa/6N22pU/6jBXteH16mS5/q',
                'role'              => 'applicant',
                'phone'             => '084128395122',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:11',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 9,
                'name'              => 'Madeline Pollich',
                'email'             => 'fletcher.von@example.net',
                'password_hash'     => '$2y$12$ShIw83xYrJiKnTnQTys.8OgtGHWTYIbqL90q3H/Wrowx.JJttrPuq',
                'role'              => 'applicant',
                'phone'             => '088445356905',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:11',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 10,
                'name'              => 'Margot Goyette',
                'email'             => 'parker.shaina@example.org',
                'password_hash'     => '$2y$12$LLzv1iVqPPV2QijEZLwJ5O4TBypFy2/w5CbhGQAffa5JqHe.evVz2',
                'role'              => 'applicant',
                'phone'             => '082737189889',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:12',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 11,
                'name'              => 'Lucile Bogan V',
                'email'             => 'estell82@example.org',
                'password_hash'     => '$2y$12$5w0oMZnN58U9bxED.NZii.XYloKxPtgd4d.SOFekl6bsGGUVjxuPy',
                'role'              => 'applicant',
                'phone'             => '086932306804',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:12',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 12,
                'name'              => 'Alf Schroeder',
                'email'             => 'pmccullough@example.net',
                'password_hash'     => '$2y$12$.8k4qG8VlCbAcPOBO5PR4OvIz44MygPGN3CYu56NN/Hls211atl42',
                'role'              => 'applicant',
                'phone'             => '081026233517',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:12',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 13,
                'name'              => 'Jerrold Hirthe',
                'email'             => 'ondricka.loraine@example.org',
                'password_hash'     => '$2y$12$Jv6o/NLoOE10pCcg40Q08.tw6pNrcj..ukdKXlSbnuHJIMfv8m7am',
                'role'              => 'applicant',
                'phone'             => '087914322352',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:13',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 14,
                'name'              => 'Betsy Deckow',
                'email'             => 'alysson.deckow@example.com',
                'password_hash'     => '$2y$12$pw7Py4tU830bjoyMSGDFDuZsx84LQA6Lsn4INOhezEM8Hvlq5CzDq',
                'role'              => 'applicant',
                'phone'             => '086117054738',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:13',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            [
                'id'                => 15,
                'name'              => 'Prof. Reginald King',
                'email'             => 'raynor.lavinia@example.com',
                'password_hash'     => '$2y$12$oqyZXgO1E3aQ2rAm9m5NQ.ufxc//cL6b.WBIQ6P6w4K6X3l30WTSS',
                'role'              => 'applicant',
                'phone'             => '080824418455',
                'is_active'         => 1,
                'email_verified_at' => '2026-03-25 18:18:13',
                'remember_token'    => null,
                'created_at'        => '2026-03-25 18:18:13',
                'updated_at'        => '2026-03-25 18:18:13',
            ],
            // ─── Akun HR Master (dibuat via seeder untuk keamanan, tanpa register) ───
            [
                'id'                => 16,
                'name'              => 'Eco Green HR Master',
                'email'             => 'ecorgeen@gmail.com',
                'password_hash'     => Hash::make('12345678'),
                'role'              => 'hr_master',
                'phone'             => null,
                'is_active'         => 1,
                'email_verified_at' => now(),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            // ─── Akun Pelamar Shin (dibuat via seeder untuk keamanan, tanpa register) ───
            [
                'id'                => 17,
                'name'              => 'Shin',
                'email'             => 'nouzenshin@gmail.com',
                'password_hash'     => Hash::make('12345678'),
                'role'              => 'applicant',
                'phone'             => null,
                'is_active'         => 1,
                'email_verified_at' => now(),
                'remember_token'    => null,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
        ]);
    }
}
