<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkExperiencesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('work_experiences')->insert([
            ['id' => 1,  'user_id' => 3,  'company_name' => 'Walker, Kris and Effertz',              'position' => 'Teacher Assistant',                          'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 2,  'user_id' => 3,  'company_name' => 'Reinger Ltd',                           'position' => 'Talent Director',                            'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 3,  'user_id' => 4,  'company_name' => 'Oberbrunner-Kautzer',                   'position' => 'Pewter Caster',                              'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 4,  'user_id' => 4,  'company_name' => 'Swift-Rosenbaum',                       'position' => 'Private Sector Executive',                   'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 5,  'user_id' => 5,  'company_name' => 'Swift-Dach',                            'position' => 'Political Science Teacher',                  'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 6,  'user_id' => 5,  'company_name' => 'Moen LLC',                              'position' => 'Rail Transportation Worker',                 'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 7,  'user_id' => 6,  'company_name' => 'Dicki Ltd',                             'position' => 'Municipal Fire Fighting Supervisor',         'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 8,  'user_id' => 6,  'company_name' => 'Kozey, Kutch and Glover',               'position' => 'Business Development Manager',               'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 9,  'user_id' => 7,  'company_name' => 'Stiedemann, Turner and VonRueden',      'position' => 'Mechanical Equipment Sales Representative', 'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 10, 'user_id' => 7,  'company_name' => 'Simonis-Daniel',                        'position' => 'Office and Administrative Support Worker',  'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:13'],
            ['id' => 11, 'user_id' => 8,  'company_name' => "Thiel-O'Reilly",                        'position' => 'Carver',                                    'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 12, 'user_id' => 8,  'company_name' => 'Little-Torphy',                         'position' => 'Biological Technician',                     'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 13, 'user_id' => 9,  'company_name' => 'Reilly LLC',                            'position' => 'Marine Oiler',                              'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 14, 'user_id' => 9,  'company_name' => 'Herman-Kassulke',                       'position' => 'Manager Tactical Operations',               'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 15, 'user_id' => 10, 'company_name' => 'Lindgren Inc',                          'position' => 'Range Manager',                             'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 16, 'user_id' => 10, 'company_name' => 'Moen-Gulgowski',                        'position' => 'Rolling Machine Setter',                    'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 17, 'user_id' => 11, 'company_name' => 'Hegmann, Schiller and Nikolaus',        'position' => 'Financial Examiner',                        'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 18, 'user_id' => 11, 'company_name' => 'Kilback, Dach and Bergnaum',            'position' => 'GED Teacher',                               'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 19, 'user_id' => 12, 'company_name' => 'Koss-Beatty',                           'position' => 'Hand Presser',                              'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 20, 'user_id' => 12, 'company_name' => 'Kiehn, Jast and Kuhic',                 'position' => 'Wellhead Pumper',                           'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 21, 'user_id' => 13, 'company_name' => 'Schuppe, Roob and Little',              'position' => 'Postsecondary Teacher',                     'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 22, 'user_id' => 13, 'company_name' => 'Hilpert Group',                         'position' => 'Hunter and Trapper',                        'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 23, 'user_id' => 14, 'company_name' => 'Herman-Shields',                        'position' => 'Ticket Agent',                              'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 24, 'user_id' => 14, 'company_name' => 'DuBuque-Heidenreich',                   'position' => 'Sewing Machine Operator',                   'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 25, 'user_id' => 15, 'company_name' => 'Pouros-Parisian',                       'position' => 'Stonemason',                                'start_date' => '2022-01-01', 'end_date' => '2023-12-31', 'is_current' => 0, 'description' => 'Bertanggung jawab dalam pengelolaan sistem dan pelaporan rutin.', 'created_at' => '2026-03-26 01:18:14'],
            ['id' => 26, 'user_id' => 15, 'company_name' => 'Breitenberg-Krajcik',                   'position' => 'Mechanical Drafter',                        'start_date' => '2024-01-01', 'end_date' => null,         'is_current' => 1, 'description' => 'Mengelola proses operasional dan koordinasi tim.', 'created_at' => '2026-03-26 01:18:14'],
        ]);
    }
}
